#ifndef FCGEOMETRYINTERFACEAPI_H
#define FCGEOMETRYINTERFACEAPI_H
#include <QtCore/QtGlobal>


#if defined(FCGEOMETRYINTERFACE_BUILDLIB)
#define FCGEOMETRYINTERFACE_API		Q_DECL_EXPORT
#else
#define FCGEOMETRYINTERFACE_API		Q_DECL_IMPORT
#endif
#endif // FCGEOMETRYINTERFACEAPI_H
