#ifndef FCMESHGENINTERFACEAPI_H
#define FCMESHGENINTERFACEAPI_H
#include <QtCore/QtGlobal>

#if defined(FCMESHGENINTERFACE_BUILDLIB)
#  define FCMESHGENINTERFACE_API Q_DECL_EXPORT
#else
#  define FCMESHGENINTERFACE_API Q_DECL_IMPORT
#endif
#endif // FCMESHGENINTERFACEAPI_H
