#ifndef FCMESHINTERFACEAPI_H
#define FCMESHINTERFACEAPI_H
#include <QtCore/QtGlobal>

#if defined(FCMESHINTERFACE_BUILDLIB)
#  define FCMESHINTERFACE_API Q_DECL_EXPORT
#else
#  define FCMESHINTERFACE_API Q_DECL_IMPORT
#endif
#endif // FCMESHINTERFACEAPI_H
