#ifndef FCACTIONSOPERATORAPI_H
#define FCACTIONSOPERATORAPI_H
#include <QtCore/QtGlobal>

#if defined(FCACTIONSOPERATOR_BUILDLIB)
#  define FCACTIONSOPERATOR_API Q_DECL_EXPORT
#else
#  define FCACTIONSOPERATOR_API Q_DECL_IMPORT
#endif
#endif // FCACTIONSOPERATORAPI_H
