#ifndef FCMODELINTERFACEAPI_H
#define FCMODELINTERFACEAPI_H
#include <QtCore/QtGlobal>


#if defined(FCMODELINTERFACE_BUILDLIB)
#define FCMODELINTERFACE_API		Q_DECL_EXPORT
#else
#define FCMODELINTERFACE_API		Q_DECL_IMPORT
#endif

#endif // FCMODELINTERFACEAPI_H
