#ifndef FCVTKGRAPHADAPTORAPI_H
#define FCVTKGRAPHADAPTORAPI_H
#include <QtCore/QtGlobal>

#if defined(FCVTKGRAPHADAPTOR_BUILDLIB)
#define FCVTKGRAPHADAPTOR_API Q_DECL_EXPORT
#else
#define FCVTKGRAPHADAPTOR_API Q_DECL_IMPORT
#endif
#endif // FCVTKGRAPHADAPTORAPI_H
