#ifndef FCRENDERWINDOWVTKAPI_H
#define FCRENDERWINDOWVTKAPI_H
#include <QtCore/QtGlobal>

#if defined(FCRENDERWINDOWVTK_BUILDLIB)
#define FCRENDERWINDOWVTK_API Q_DECL_EXPORT
#else
#define FCRENDERWINDOWVTK_API Q_DECL_IMPORT
#endif
#endif // FCRENDERWINDOWVTKAPI_H
