#ifndef FCGEOMETRYCOMMANDAPI_H
#define FCGEOMETRYCOMMANDAPI_H

#include <QtCore/QtGlobal>


#if defined(FCGEOMETRYCMD_BUILDLIB)
#define FCGEOMETRYCMD_API		Q_DECL_EXPORT
#else
#define FCGEOMETRYCMD_API		Q_DECL_IMPORT
#endif
#endif // FCGEOMETRYCOMMANDAPI_H
