/*
 * Copyright (c) 2020-2025, Qingdao Digital Intelligent Ship & Ocean Technology Co., Ltd.
 * All rights reserved.
 *
 * This file is part of FastCAE and is distributed under the terms of the
 * BSD 3-Clause License. See the LICENSE file in the project root for details.
 */

/**
 * @file FCOCCModelMisc.cpp
 * @brief OCC 其余几何命令桩实现（update 暂为 stub）
 */
#include "FCOCCModelMisc.h"
#include <FCGeometryInterface/FCGeoEnum.h>

namespace OCC {

#define FCOCC_MISC_GET_TYPE(Class, Enum) \
    FC::FCGeoEnum::FITKGeometryComType Class::getGeometryCommandType() { return FC::FCGeoEnum::Enum; }
#define FCOCC_MISC_UPDATE(Class) \
    bool Class::update() { return false; }

FCOCC_MISC_GET_TYPE(FCOCCModelImportFlattenAssembly, FGTImportFlattenAssembly)
FCOCC_MISC_UPDATE(FCOCCModelImportFlattenAssembly)

FCOCC_MISC_GET_TYPE(FCOCCModelOperLine, FGTMergeLine)
FCOCC_MISC_UPDATE(FCOCCModelOperLine)

FCOCC_MISC_GET_TYPE(FCOCCModelOperFaceRemoveFace, FGTRemoveFace)
FCOCC_MISC_UPDATE(FCOCCModelOperFaceRemoveFace)

FCOCC_MISC_GET_TYPE(FCOCCModelOperFaceFillGaps, FGTFillGapsFace)
FCOCC_MISC_UPDATE(FCOCCModelOperFaceFillGaps)

FCOCC_MISC_GET_TYPE(FCOCCModelOperFaceDeleteFloatingEdge, FGTDeleteFloatingEdge)
FCOCC_MISC_UPDATE(FCOCCModelOperFaceDeleteFloatingEdge)

FCOCC_MISC_GET_TYPE(FCOCCModelOperImprintSolid, FGTImprintSolid)
FCOCC_MISC_UPDATE(FCOCCModelOperImprintSolid)

FCOCC_MISC_GET_TYPE(FCOCCModelOperAddCompound, FGTCompoundAppendShape)
FCOCC_MISC_UPDATE(FCOCCModelOperAddCompound)

FCOCC_MISC_GET_TYPE(FCOCCModelOperRemoveCompound, FGTCompoundRemoveShape)
FCOCC_MISC_UPDATE(FCOCCModelOperRemoveCompound)

FCOCC_MISC_GET_TYPE(FCOCCModelMiddleOperLine, FGTSplitByMiddlePositionLine)
FCOCC_MISC_UPDATE(FCOCCModelMiddleOperLine)

FCOCC_MISC_GET_TYPE(FCOCCModelStitch, FGTStitch)
FCOCC_MISC_UPDATE(FCOCCModelStitch)

FCOCC_MISC_GET_TYPE(FCOCCModelExportTopos, FGTExportTopos)
FCOCC_MISC_UPDATE(FCOCCModelExportTopos)

FCOCC_MISC_GET_TYPE(FCOCCGeoSketchDeleter, FGTSketchDeleter)
FCOCC_MISC_UPDATE(FCOCCGeoSketchDeleter)

FCOCC_MISC_GET_TYPE(FCOCCModelRectangularPattern, FGTRectangularPattern)
FCOCC_MISC_UPDATE(FCOCCModelRectangularPattern)

FCOCC_MISC_GET_TYPE(FCOCCModelCircularPattern, FGTCircularPattern)
FCOCC_MISC_UPDATE(FCOCCModelCircularPattern)

FCOCC_MISC_GET_TYPE(FCOCCCurveSplitter, FGTCurveSplitter)
FCOCC_MISC_UPDATE(FCOCCCurveSplitter)

FCOCC_MISC_GET_TYPE(FCOCCSurfaceSplitter, FGTSurfaceSplitter)
FCOCC_MISC_UPDATE(FCOCCSurfaceSplitter)

FCOCC_MISC_GET_TYPE(FCOCCSolidSplitter, FGTSolidSplitter)
FCOCC_MISC_UPDATE(FCOCCSolidSplitter)

FCOCC_MISC_GET_TYPE(FCOCCStiffener, FGTStiffener)
FCOCC_MISC_UPDATE(FCOCCStiffener)

FCOCC_MISC_GET_TYPE(FCOCCModelNearestPointLine, FGTNearestPointLine)
FCOCC_MISC_UPDATE(FCOCCModelNearestPointLine)

FCOCC_MISC_GET_TYPE(FCOCCModelExtractCenter, FGTExtractCenter)
FCOCC_MISC_UPDATE(FCOCCModelExtractCenter)

FCOCC_MISC_GET_TYPE(FCOCCModelFromMesh, FGTModelFromMesh)
FCOCC_MISC_UPDATE(FCOCCModelFromMesh)

FCOCC_MISC_GET_TYPE(FCOCCModelRepairSmallEdges, FGTRepairSmallEdges)
FCOCC_MISC_UPDATE(FCOCCModelRepairSmallEdges)

FCOCC_MISC_GET_TYPE(FCOCCModelRepairSmallFaces, FGTRepairSmallFaces)
FCOCC_MISC_UPDATE(FCOCCModelRepairSmallFaces)

FCOCC_MISC_GET_TYPE(FCOCCModelCoverEdges, FGTCoverEdges)
FCOCC_MISC_UPDATE(FCOCCModelCoverEdges)

FCOCC_MISC_GET_TYPE(FCOCCModelReplaceFaces, FGTReplaceFaces)
FCOCC_MISC_UPDATE(FCOCCModelReplaceFaces)

FCOCC_MISC_GET_TYPE(FCOCCModelPartitionEdgeWithParameter, FGTPartitionEdgeWithParameter)
FCOCC_MISC_UPDATE(FCOCCModelPartitionEdgeWithParameter)

FCOCC_MISC_GET_TYPE(FCOCCModelPartitionEdgeWithPoint, FGTPartitionEdgeWithPoint)
FCOCC_MISC_UPDATE(FCOCCModelPartitionEdgeWithPoint)

FCOCC_MISC_GET_TYPE(FCOCCModelPartitionEdgeWithDatumPlane, FGTPartitionEdgeWithDatumPlane)
FCOCC_MISC_UPDATE(FCOCCModelPartitionEdgeWithDatumPlane)

FCOCC_MISC_GET_TYPE(FCOCCModelPartitionFaceWithSketch, FGTPartitionFaceWithSketch)
FCOCC_MISC_UPDATE(FCOCCModelPartitionFaceWithSketch)

FCOCC_MISC_GET_TYPE(FCOCCModelPartitionFaceWithTwoPoints, FGTPartitionFaceWithTwoPoints)
FCOCC_MISC_UPDATE(FCOCCModelPartitionFaceWithTwoPoints)

FCOCC_MISC_GET_TYPE(FCOCCModelPartitionFaceWithDatumPlane, FGTPartitionFaceWithDatumPlane)
FCOCC_MISC_UPDATE(FCOCCModelPartitionFaceWithDatumPlane)

FCOCC_MISC_GET_TYPE(FCOCCModelPartitionFaceWithCurvedPath, FGTPartitionFaceWithCurvedPath)
FCOCC_MISC_UPDATE(FCOCCModelPartitionFaceWithCurvedPath)

FCOCC_MISC_GET_TYPE(FCOCCModelPartitionFaceWithExtendFace, FGTPartitionFaceWithExtendFace)
FCOCC_MISC_UPDATE(FCOCCModelPartitionFaceWithExtendFace)

FCOCC_MISC_GET_TYPE(FCOCCModelPartitionFaceWithIntersectFace, FGTPartitionFaceWithIntersectFace)
FCOCC_MISC_UPDATE(FCOCCModelPartitionFaceWithIntersectFace)

FCOCC_MISC_GET_TYPE(FCOCCModelPartitionFaceWithProjectEdges, FGTPartitionFaceWithProjectEdges)
FCOCC_MISC_UPDATE(FCOCCModelPartitionFaceWithProjectEdges)

FCOCC_MISC_GET_TYPE(FCOCCModelPartitionSolidWithPlane, FGTPartitionSolidWithPlane)
FCOCC_MISC_UPDATE(FCOCCModelPartitionSolidWithPlane)

FCOCC_MISC_GET_TYPE(FCOCCModelPartitionSolidWithExtendFace, FGTPartitionSolidWithExtendFace)
FCOCC_MISC_UPDATE(FCOCCModelPartitionSolidWithExtendFace)

FCOCC_MISC_GET_TYPE(FCOCCModelPartitionSolidWithSweepEdge, FGTPartitionSolidWithSweepEdge)
FCOCC_MISC_UPDATE(FCOCCModelPartitionSolidWithSweepEdge)

FCOCC_MISC_GET_TYPE(FCOCCModelPartitionSolidWithSketchPlanar, FGTPartitionSolidWithSketchPlanar)
FCOCC_MISC_UPDATE(FCOCCModelPartitionSolidWithSketchPlanar)

#undef FCOCC_MISC_GET_TYPE
#undef FCOCC_MISC_UPDATE

} // namespace OCC
